
- name: Prep for AEM
  hosts: all
  gather_facts: true

  tasks:
    - name: Install JDK 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install Maven
      apt:
        name: maven
        state: latest

    - name: Copy Maven settings.xml and take backup of original
      copy:
        src: "/vagrant/maven-settings.xml"
        dest: "/etc/maven/settings.xml"
        backup: yes

    - name: Run Maven setup script - will fail if not on Telstra local network
      script: mvn-setup.sh
